import type { RecommendedBook } from '../types';

export const bookData: RecommendedBook[] = [
    { id: 'book-cpc-guide', title: 'Official CPC® Certification Study Guide (AAPC)', description: 'AAPC\'s official CPC exam study guide — anatomy, medical terminology, ICD-10-CM, CPT, HCPCS, practice questions and exam tips.', imageUrl: 'https://www.coding-online.net/wp-content/uploads/2024/04/cpc-study-guide.jpg', affiliateLinks: { com: 'https://www.amazon.com/dp/1635278910?tag=mykada-20', in: 'https://www.amazon.in/dp/1635278910?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1285427998?tag=medical0f1-21' } },
    { id: 'book-icd10-cm', title: "Buck's ICD-10-CM for Physicians 2026", description: 'Physician-focused ICD-10-CM code manual (full-color, guidelines and examples).', imageUrl: 'https://www.coding-online.net/wp-content/uploads/2024/04/icd-10-cm-physicians.jpg', affiliateLinks: { com: 'https://www.amazon.com/dp/0443380783?tag=mykada-20', in: 'https://www.amazon.in/dp/0443380783?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/0443380783?tag=medical0f1-21' } },
    { id: 'book-cpt-pro', title: 'AMA CPT® Professional 2026', description: 'Official Current Procedural Terminology (CPT) codebook from the American Medical Association.', imageUrl: 'https://www.coding-online.net/wp-content/uploads/2024/04/cpt-professional.jpg', affiliateLinks: { com: 'https://www.amazon.com/dp/1640163354?tag=mykada-20', in: 'https://www.amazon.in/dp/1640163354?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1640163354?tag=medical0f1-21' } },
    { id: 'book-hcpcs-level2', title: 'HCPCS Level II Professional 2026', description: 'Comprehensive guide for HCPCS Level II codes used for supplies, equipment, and drugs.', imageUrl: 'https://www.coding-online.net/wp-content/uploads/2024/04/hcpcs-level-2.jpg', affiliateLinks: { com: 'https://www.amazon.com/dp/1622029947?tag=mykada-20', in: 'https://www.amazon.in/dp/1622029947?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1622029947?tag=medical0f1-21' } },
    { id: 'book-medical-billing', title: 'Medical Billing & Coding For Dummies', description: 'An easy-to-understand guide covering the basics of medical billing and coding.', imageUrl: 'https://www.coding-online.net/wp-content/uploads/2024/04/coding-for-dummies.jpg', affiliateLinks: { com: 'https://www.amazon.com/dp/1119750393?tag=mykada-20', in: 'https://www.amazon.in/dp/1119750393?tag=httpcodingonl-21', ae: 'https://www.amazon.ae/dp/1119750393?tag=medical0f1-21' } }
];
